const quiz_data = String.raw`{

"1": {"question":
	"(1_Jogi_Alapok) Az alább felsoroltak közül melyik nem jellemző a társadalmi és jogi normákra?",
	"a": "A hipotetikus szerkezet.",
	"b": "A szankció.",
	"c": "A múltra irányultság.",
	"d": "Mindegyik jellemző.",
	"answer": "c"},
"2": {"question":
	"Az alábbiak közül melyik nem tartozik a társadalmi normák lényeges mozzanatai közé?",
	"a": "A magatartás leírása.",
	"b": "A magatartás minősítése. (tilos, kötelező stb.)",
	"c": "A következmények leírása.",
	"d": "Mindegyik oda tartozik.",
	"answer": "d"},
"3": {"question":
	"Melyik állítás a legjellemzőbb a jogi normákra?",
	"a": "A társadalom alkotja, érvényesülését az állam biztosítja.",
	"b": "Az állam alkotja, érvényesülését az állam biztosítja.",
	"c": "Az állam alkotja, érvényesülését a társadalom biztosítja.",
	"d": "A társadalom alkotja, érvényesülését a társadalom biztosítja.",
	"answer": "b"},
"4": {"question":
	"Az alábbi 3 állítás (a,b,c) közül melyik hamis?",
	"a": "A jogi normákat gyorsabban meg lehet változtatni, mint a társadalmi normákat.",
	"b": "Az erkölcsi normák szankciórendszerét a társadalmi nyomás jellemzi.",
	"c": "A jogi norma az emberek formális magatartására irányul.",
	"d": "Mindhárom előző állítás igaz.",
	"answer": "d"},
"5": {"question":
	"Az alábbi 3 állítás (a,b,c) közül melyik hamis?",
	"a": "A társadalmi normákat gyorsabban meg lehet változtatni, mint a jogi normákat.",
	"b": "Az erkölcsi normák szankciórendszerét a társadalmi nyomás jellemzi.",
	"c": "A jogi norma az emberek formális magatartására irányul.",
	"d": "Mindhárom előző állítás igaz.",
	"answer": "a"},
"6": {"question":
	"Hányféle módját ismerjük a jogképződésnek, a jogi normák létrejöttének? Sorolja is fel ezeket.",
	"a": "2 jogalkalmazói, jogalkotói",
	"b": "3 szokásjogi, jogalkalmazói, jogalkotói",
	"c": "4 vallásjogi, szokásjogi, jogalkalmazói, jogalkotói",
	"d": "5 vallásjogi, szokásjogi, jogalkalmazói, jogalkotói, veszélyhelyzeti-jogalkotói",
	"answer": "b"},
"7": {"question":
	"Melyik jogképződési mód során jön létre a precedensjog?",
	"a": "Szokásjogi jogképződés útján.",
	"b": "Jogalkalmazói jogképződés útján.",
	"c": "Jogalkotói jogképződés útján.",
	"d": "Megyegyezés útján.",
	"answer": "b"},
"8": {"question":
	"A jog melyik funkciójának megvalósítását biztosítja elsősorban a bírósági szervezet?",
	"a": "Az integráló funkciót.",
	"b": "A konfliktus-feloldó funkciót.",
	"c": "A társadalomszervező funkciót.",
	"d": "Egyik funkció megvalósítását sem biztosítja.",
	"answer": "b"},
"9": {"question":
	"A jog melyik funkciójának megvalósítását biztosítják elsősorban a közigazgatási hatóságok?",
	"a": "Az integráló funkciót.",
	"b": "A konfliktus-feloldó funkciót.",
	"c": "A társadalomszervező funkciót.",
	"d": "Egyik funkció megvalósítását sem biztosítják.",
	"answer": "c"},
"10": {"question":
	"Melyik állítás hamis?",
	"a": "Az anyagi jogforrás azt a szervet jelenti, amelytől a jogi norma ered.",
	"b": "A belső jogforrás ugyanazt jelenti, mint az alaki jogforrás.",
	"c": "Az alaki jogforrás azt a formát jelenti, amelyben a jogi norma megjelenik.",
	"d": "Elsődleges jogforrás maga a jogalkotó hatalom, az állam. ",
	"answer": "b"},
"11": {"question":
	"Melyik állítás hamis?",
	"a": "Az anyagi jogforrás azt a szervet jelenti, amelytől a jogi norma ered.",
	"b": "Az alaki jogforrás azt a formát jelenti, amelyben a jogi norma megjelenik.",
	"c": "Elsődleges jogforrás maga a jogalkotó hatalom, az állam.",
	"d": "Mindhárom előző állítás igaz.",
	"answer": "d"},
"12": {"question":
	"Mit mond ki a \"Lex superior derogat legi inferiori\" alapelv?",
	"a": "A később megalkotott jogszabály a korábbinak a hatályát lerontja.",
	"b": "A speciális jogszabályt kell alkalmazni az általánossal szemben.",
	"c": "Alacsonyabb szintű jogszabály nem ellenkezhet magasabb szintűvel.",
	"d": "Jogszabállyal ellentétes másik jogszabályt nem lehet alkotni.",
	"answer": "c"},
"13": {"question":
	"Mit mond ki a \"Lex specialis derogat legi generali\" alapelv?",
	"a": "A később megalkotott jogszabály a korábbinak a hatályát lerontja.",
	"b": "A speciális jogszabályt kell alkalmazni az általánossal szemben.",
	"c": "Alacsonyabb szintű jogszabály nem ellenkezhet magasabb szintűvel.",
	"d": "Jogszabállyal ellentétes másik jogszabályt nem lehet alkotni.",
	"answer": "b"},
"14": {"question":
	"Mit mond ki a \"Lex posterior derogat legi priori\" alapelv?",
	"a": "A később megalkotott jogszabály a korábbinak a hatályát lerontja.",
	"b": "A speciális jogszabályt kell alkalmazni az általánossal szemben.",
	"c": "Alacsonyabb szintű jogszabály nem ellenkezhet magasabb szintűvel.",
	"d": "Jogszabállyal ellentétes másik jogszabályt nem lehet alkotni.",
	"answer": "a"},
"15": {"question":
	"Az alábbi jogszabályok közül melyik tartozik az anyagi jog körébe?",
	"a": "A büntetőeljárásról szóló törvény.",
	"b": "A polgári eljárásról szóló törvény.",
	"c": "A közigazgatási eljárásról szóló törvény.",
	"d": "Egyik sem.",
	"answer": "d"},
"16": {"question":
	"Az alábbi jogszabályok közül melyik tartozik az anyagi jog körébe?",
	"a": "A büntetőeljárásról szóló törvény.",
	"b": "A polgári törvénykönyv.",
	"c": "A közigazgatási eljárásról szóló törvény.",
	"d": "Egyik sem.",
	"answer": "b"},
"17": {"question":
	"Az alábbi jogszabályok közül melyik tartozik az alaki jog körébe?",
	"a": "A büntető törvénykönyv.",
	"b": "A büntetőeljárásról szóló törvény.",
	"c": "A polgári törvénykönyv.",
	"d": "A munka törvénykönyve.",
	"answer": "b"},
"18": {"question":
	"Melyik állítás igaz?",
	"a": "A polgári jog a közjog területéhez tartozik.",
	"b": "A büntetőjog a magánjog területéhez tartozik.",
	"c": "A kereskedelmi jog a magánjog területéhez tartozik.",
	"d": "A közigazgatási jog a magánjog területéhez tartozik.",
	"answer": "c"},
"19": {"question":
	"Mit nevezünk joghézagnak?",
	"a": "Amikor a bíróság nem tud választani két alkalmazandó jogszabály közül.",
	"b": "Amikor két jogszabály egymásnak ellentmondó.",
	"c": "Amikor a jog nem tartalmaz választ egy adott kérdésre.",
	"d": "Amikor nincs olyan bíróság, amelyik dönthetne egy adott kérdésben.",
	"answer": "c"},
"20": {"question":
	"Melyik jogág szabályozási körébe tartozik a gyülekezési jog?",
	"a": "Polgári jog.",
	"b": "Alkotmányjog.",
	"c": "Munkajog.",
	"d": "Közigazgatási jog.",
	"answer": "b"},
"21": {"question":
	"Melyik állítás igaz az angolszász jogrendszerekre?",
	"a": "A jogalkotás és jogalkalmazás szférája mereven elválik egymástól.",
	"b": "A szabályok jelentős része nincs törvénybe foglalva.",
	"c": "E jogrendszerek pillérei az írott jogforrások.",
	"d": "A joganyag önálló, zárt rendszert alkot.",
	"answer": "b"},
"22": {"question":
	"Melyik jogrendszerre a leginkább jellemző, hogy politikailag erősen kötött?",
	"a": "Az angolszász jogrendszerekre.",
	"b": "A szocialista jogrendszerekre.",
	"c": "A kontinentális jogrendszerekre.",
	"d": "A vallási alapú jogrendszerekre.",
	"answer": "b"},
"23": {"question":
	"Melyik állítás igaz a kontinentális jogrendszerekre?",
	"a": "A bírónak jelentős szerepe van a jogalkotásban.",
	"b": "A jogszabályok kevésbé elvontak és általánosak.",
	"c": "A joganyag önálló, zárt rendszert alkot.",
	"d": "A jogszabályok egy-egy vitás ügy eldöntésekor keletkeznek.",
	"answer": "c"},
"24": {"question":
	"Melyik állítás nem igaz a szocialista jogrendszerekre vonatkozóan?",
	"a": "A politika közvetlenül befolyásolja a jogot.",
	"b": "A magánjognak kisebb a jelentősége.",
	"c": "A jogi túlszabályozás jellemző.",
	"d": "Mindegyik fenti állítás igaz rá.",
	"answer": "d"},
"25": {"question":
	"Melyik állítás nem igaz a szocialista jogrendszerekre vonatkozóan?",
	"a": "A politika közvetlenül befolyásolja a jogot.",
	"b": "A magánjognak nagy jelentősége van.",
	"c": "A jogi túlszabályozás jellemző.",
	"d": "Mindegyik fenti állítás igaz rá.",
	"answer": "b"},
"26": {"question":
	"(2_Jogszabálytan) A tényeknek olyan összessége, amelyhez valamilyen joghatás fűződik, ...",
	"a": "a jogi norma diszpozíciója.",
	"b": "a jogi norma szankciója.",
	"c": "a jogi norma hipotézise.",
	"d": "a jogi norma jogkövetkezménye.",
	"answer": "c"},
"27": {"question":
	"Az a magatartási szabály, amelyet a jogalkotó a jogalany számára előír, ...",
	"a": "a jogi norma diszpozíciója.",
	"b": "a jogi norma szankciója.",
	"c": "a jogi norma hipotézise.",
	"d": "a jogi norma jogkövetkezménye.",
	"answer": "a"},
"28": {"question":
	"Egészítse ki a kipontozott részt. A ... esetén a jogalkotó nem határozza meg, hogy mely tényállás esetén szükséges  a normában meghatározott magatartást tanúsítani, csupán példaszerűen felsorolja azokat.",
	"a": "zárt tényállás",
	"b": "nyitott tényállás",
	"c": "parancsoló norma",
	"d": "diszpozitív norma",
	"answer": "b"},
"29": {"question":
	"Milyenfajta rendelkezés nem fordulhat elő a jogi norma diszpozíciójában?",
	"a": "tiltó",
	"b": "parancsoló",
	"c": "megengedő",
	"d": "mindhárom előfordulhat",
	"answer": "d"},
"30": {"question":
	"Melyik állítás igaz?",
	"a": "A lopás bűncselekménye mindig vagyoni jellegű szankciót von maga után.",
	"b": "A jogi norma megsértése nem járhat személyi jellegű szankcióval.",
	"c": "A szankció egyidejűleg mindig csak egyféle joghátrányt alkalmazhat.",
	"d": "Az érvénytelenség a szankciók egyik típusa.",
	"answer": "d"},
"31": {"question":
	"Melyik állítás igaz?",
	"a": "Az apaság vélelme nem megdönthető.",
	"b": "A fikció esetén lehetőség van az ellenkező bizonyítására.",
	"c": "A 14. életévét be nem töltött személy cselekvőképtelenségének vélelme megdönthető.",
	"d": "A vélelem legfontosabb jogi következménye a bizonyítási teher megfordítása.",
	"answer": "d"},
"32": {"question":
	"Melyik állítás igaz?",
	"a": "Az apaság vélelme megdönthető.",
	"b": "A fikció esetén lehetőség van az ellenkező bizonyítására.",
	"c": "A 14. életévét be nem töltött személy cselekvőképtelenségének vélelme megdönthető.",
	"d": "A fikció legfontosabb jogi következménye a bizonyítási teher megfordítása.",
	"answer": "a"},
"33": {"question":
	"Egy jogszabály érvényességének hány feltétele van? Sorolja is fel ezeket.",
	"a": "3, a következők: megfelelő szerv; megfelelő eljárás; hierarchiába illeszkedés;",
	"b": "4, a következők: megfelelő szerv; megfelelő eljárás; hierarchiába illeszkedés; kihirdetés",
	"c": "2, a következők: megfelelő szerv; megfelelő eljárás",
	"d": "5, a következők: megfelelő szerv; megfelelő eljárás; hierarchiába illeszkedés; kihirdetés; hatályosság",
	"answer": "b"},
"34": {"question":
	"Melyik állítás igaz?",
	"a": "A jogszabály időbeli hatálya nem lehet visszamenőleges.",
	"b": "A magyar jogszabályok területi hatálya Magyarország teljes területe.",
	"c": "Egy jogszabály lehet egyidejűleg érvényes, de nem hatályos.",
	"d": "Egy jogszabály lehet egyidejűleg hatályos és érvénytelen.",
	"answer": "c"},
"35": {"question":
	"Melyik állítás igaz?",
	"a": "Egy magyar jogszabály minden magyar állampolgárra vonatkozik.",
	"b": "Egy jogszabály csak a jövőre vonatkozóan állapíthat meg kötelezettséget.",
	"c": "A személyi hatály azt határozza meg, hogy ki alkotta a jogszabályt.",
	"d": "Egy magyar jogszabály csak magyar állampolgárokra vonatkozik.",
	"answer": "b"},
"36": {"question":
	"Melyik állítás igaz?",
	"a": "Egy jogszabály nem érvényes, ha a köztársasági elnök nem írta alá.",
	"b": "Egy törvény nem érvényes, ha ellenkezik egy rendelettel.",
	"c": "Egy jogszabály nem érvényes, ha nem hirdették ki.",
	"d": "Mindhárom fenti állítás hamis.",
	"answer": "c"},
"37": {"question":
	"Melyik állítás igaz?",
	"a": "Egy jogszabály nem érvényes, ha a köztársasági elnök nem írta alá.",
	"b": "Egy rendelet nem érvényes, ha ellenkezik egy törvénnyel.",
	"c": "Egy jogszabály akkor is érvényes, ha nem hirdették ki.",
	"d": "Mindhárom fenti állítás hamis.",
	"answer": "b"},
"38": {"question":
	"Melyik állítás igaz?",
	"a": "A jogszabályok tudományos értelmezésének csak az adott ügyben van kötelező ereje.",
	"b": "A jogalkotói jogszabály értelmezés minden címzettre nézve kötelező.",
	"c": "A jogalkalmazói jogszabály értelmezésnek nincs kötelező ereje.",
	"d": "A jogalkotói jogszabály értelmezés tilos. ",
	"answer": "b"},
"39": {"question":
	"Melyik állítás igaz?",
	"a": "A közigazgatási szervek eljárása mindig kezdeményezésre indul.",
	"b": "A jogalanyok önkéntes jogkövetését is jogalkalmazásnak tekintjük.",
	"c": "A jogalkalmazás célja mindig valamilyen jogsérelem orvoslása.",
	"d": "A jogalkalmazás utolsó lépése a tényállás megállapítása.",
	"answer": "b"},
"40": {"question":
	"Melyik nem következhet be a jogalkalmazás eredményeképpen?",
	"a": "Jogviszony keletkezése.",
	"b": "Jogviszony megszűnése.",
	"c": "Jogviszony módosulása.",
	"d": "Mindhárom fenti bekövetkezhet.",
	"answer": "d"},
"41": {"question":
	"Mely szerv biztosítja a bíróságok egységes jogalkalmazását?",
	"a": "Az alkotmánybíróság.",
	"b": "A törvényszék.",
	"c": "Az ítélőtábla.",
	"d": "A Kúria.",
	"answer": "d"},
"42": {"question":
	"Mely szerv biztosítja a bíróságok egységes jogalkalmazását?",
	"a": "Az alkotmánybíróság.",
	"b": "Az ítélőtábla.",
	"c": "A Kúria.",
	"d": "Egyik sem.",
	"answer": "c"},
"43": {"question":
	"Melyik nem tartozik a jogszabály értelmezésének módszerei közé?",
	"a": "A rendszertani értelmezés.",
	"b": "A történeti értelmezés.",
	"c": "A módszertani értelmezés.",
	"d": "A logikai értelmezés.",
	"answer": "c"},
"44": {"question":
	"A jogviszony szerkezeti elemei közé tartozik",
	"a": "a jogviszony helye.",
	"b": "a jogviszony ideje.",
	"c": "a jogviszony tartalma.",
	"d": "Egyik sem.",
	"answer": "c"},
"45": {"question":
	"Ingatlan adásvételi szerződés esetén a jogviszony tárgya",
	"a": "a vételár kifizetése.",
	"b": "a tulajdonjog átruházása.",
	"c": "az ingatlan.",
	"d": "Egyik sem.",
	"answer": "c"},
"46": {"question":
	"Melyik állítás hamis?",
	"a": "A kötelmi jogban a relatív szerkezetű jogviszonyok jellemzők.",
	"b": "A tulajdonjog abszolút szerkezetű jogviszony.",
	"c": "Ha több, mint 2 fél szerepel a szerződésben, az abszolút szerkezetű jogviszonyt eredményez.",
	"d": "A károkozás relatív szerkezetű jogviszonyt teremt.",
	"answer": "c"},
"47": {"question":
	"Melyik nem rendelkezik jogi személyiséggel?",
	"a": "Az Állam.",
	"b": "Az egyesület.",
	"c": "A társasház.",
	"d": "Az egyetem.",
	"answer": "c"},
"48": {"question":
	"Az alábbiak (a,b,c) közül melyik nem rendelkezik jogi személyiséggel?",
	"a": "Az Állam.",
	"b": "Az egyesület.",
	"c": "Az egyetem.",
	"d": "Mindegyik rendelkezik.",
	"answer": "d"},
"49": {"question":
	"Melyik állítás igaz?",
	"a": "Együttes kötelezettek bármelyikétől az egész tartozás követelhető.",
	"b": "Egyetemleges kötelezettek egyidejűleg, de arányosan kötelesek teljesíteni.",
	"c": "A kezes az adóssal fele-fele arányban köteles teljesíteni a tartozást.",
	"d": "Mindhárom fenti állítás hamis.",
	"answer": "d"},
"50": {"question":
	"(3_Személyek_Joga) Az alábbi 3 állítás (a,b,c) közül melyik hamis?",
	"a": "Aki jogképes, az önállóan köthet szerződést.",
	"b": "Aki jogképes, az jogosultságok alanya lehet.",
	"c": "Aki betöltötte a 14. életévét az jogképes.",
	"d": "Mindhárom előző állítás igaz.",
	"answer": "a"},
"51": {"question":
	"Melyik állítás igaz?",
	"a": "A jogképesség a születéssel kezdődik.",
	"b": "A jogképesség mindig a születés előtti 300-adik napon kezdődik.",
	"c": "A jogképesség mindig a fogamzástól kezdődik.",
	"d": "A magzat jogképessége feltételes.",
	"answer": "d"},
"52": {"question":
	"Melyik állítás igaz?",
	"a": "A bíróság korlátozhatja a természetes személy jogképességét.",
	"b": "A Ptk. nem korlátozhatja az ember cselekvőképességét.",
	"c": "Aki cselekvőképes, az önállóan köthet szerződést.",
	"d": "Mindhárom fenti állítás hamis.",
	"answer": "c"},
"53": {"question":
	"Az alábbi 3 állítás (a,b,c) közül melyik hamis?",
	"a": "17 éves személy is lehet nagykorú.",
	"b": "17 éves személy is lehet cselekvőképes.",
	"c": "13 éves személy is lehet korlátozottan cselekvőképes.",
	"d": "Mindhárom előző állítás igaz.",
	"answer": "c"},
"54": {"question":
	"Az alábbi 3 állítás (a,b,c) közül melyik hamis?",
	"a": "A kiskorú személy a házasságkötéssel nagykorúvá válik.",
	"b": "17 éves személy is lehet cselekvőképes.",
	"c": "A 13 éves személy minden esetben cselekvőképtelennek minősül.",
	"d": "Mindhárom előző állítás igaz.",
	"answer": "d"},
"55": {"question":
	"Az alábbi 3 állítás (a,b,c) közül melyik hamis?",
	"a": "Nagykorú személy is lehet cselekvőképtelen.",
	"b": "Kiskorú személy is lehet korlátozottan cselekvőképes.",
	"c": "A kiskorú személy házasságkötése érvénytelen.",
	"d": "Mindhárom előző állítás igaz.",
	"answer": "c"},
"56": {"question":
	"Mit nem tehet meg önállóan a korlátozottan cselekvőképes kiskorú?",
	"a": "Tetszőleges értékű ajándékot adhat.",
	"b": "Tetszőleges értékű ajándékot elfogadhat.",
	"c": "Rendelkezhet munkával szerzett jövedelmével.",
	"d": "Mindhárom fenti jognyilatkozatot megteheti önállóan.",
	"answer": "a"},
"57": {"question":
	"Melyik nem tartozik a gyám feladatai közé?",
	"a": "A gyermek gondozása, nevelése.",
	"b": "A gyermek vagyonának kezelése.",
	"c": "A gyermek törvényes képviselete.",
	"d": "Mindhárom fenti a gyám feladatai közé tartozik.",
	"answer": "d"},
"58": {"question":
	"Melyikkel nem feltétlenül kell rendelkeznie a jogi személynek?",
	"a": "Székhellyel.",
	"b": "Saját vagyonnal.",
	"c": "Telephellyel.",
	"d": "Képviselővel.",
	"answer": "c"},
"59": {"question":
	"Ki felel a jogi személy tartozásaiért?",
	"a": "A vezető tisztségviselő.",
	"b": "A döntéshozó szerv.",
	"c": "A tagok és alapítók.",
	"d": "Egyik sem.",
	"answer": "d"},
"60": {"question":
	"Mikor jön létre a jogi személy?",
	"a": "A létesítő okirat aláírásakor.",
	"b": "A bejegyzési kérelem bírósághoz történő benyújtásakor.",
	"c": "A bírósági nyilvántartásba vétel megtörténtekor.",
	"d": "A bírósági határozat kézbesítésekor.",
	"answer": "c"},
"61": {"question":
	"Ki látja el a jogi személy tulajdonosainak érdekvédelmét?",
	"a": "A könyvvizsgáló.",
	"b": "A vezető tisztségviselő.",
	"c": "A felügyelőbizottság.",
	"d": "Egyik sem.",
	"answer": "c"},
"62": {"question":
	"Ki látja el a jogi személy törvényes működésének felügyeletét?",
	"a": "Az ügyészség.",
	"b": "A felügyelőbizottság.",
	"c": "A nyilvántartó bíróság.",
	"d": "Egyik sem.",
	"answer": "c"},
"63": {"question":
	"Melyik állítás hamis?",
	"a": "Összeolvadásnál a korábbi jogi személyek megszűnnek.",
	"b": "Kiválásnál a jogi személy megszűnik.",
	"c": "Különválásnál a jogi személy megszűnik.",
	"d": "Átalakulásnál a korábbi jogi személy megszűnik.",
	"answer": "b"},
"64": {"question":
	"Melyik nem tartozik a (jogi személy) jogutód nélküli megszűnés esetei közé?",
	"a": "A tagok kimondják a megszűnést.",
	"b": "A létesítő okiratban meghatározott idő eltelik.",
	"c": "A jogi személy tartozása meghaladja a vagyonát.",
	"d": "A jogosult szerv megszünteti.",
	"answer": "c"},
"65": {"question":
	"Melyik állítás igaz?",
	"a": "Alapítvány létrehozásához legalább 10 alapító szükséges.",
	"b": "Az egyesület megszűnik, ha tagjainak száma tartósan nem éri el a 12 főt.",
	"c": "Az egyesület átalakulhat alapítvánnyá.",
	"d": "Egyik fenti állítás sem igaz.",
	"answer": "d"},
"66": {"question":
	"Melyik állítás igaz?",
	"a": "Alapítvány létrehozásához legalább 10 alapító szükséges.",
	"b": "Az egyesület megszűnik, ha tagjainak száma tartósan nem éri el a 10 főt.",
	"c": "Az alapítvány átalakulhat egyesületté.",
	"d": "Egyik fenti állítás sem igaz.",
	"answer": "b"},
"67": {"question":
	"Egyesületnél mely esetben kötelező a felügyelőbizottság létrehozása?",
	"a": "Ha a tagok több, mint negyede nem természetes személy.",
	"b": "Ha a tagok létszáma az 50 főt meghaladja.",
	"c": "Ha a könyvvizsgáló ezt kéri.",
	"d": "Egyik fenti esetben sem kötelező.",
	"answer": "d"},
"68": {"question":
	"Egyesületnél mely esetben kötelező a felügyelőbizottság létrehozása?",
	"a": "Ha a tagok több, mint fele nem természetes személy.",
	"b": "Ha a tagok létszáma az 50 főt meghaladja.",
	"c": "Ha a könyvvizsgáló ezt kéri.",
	"d": "Egyik fenti esetben sem kötelező.",
	"answer": "a"},
"69": {"question":
	"Melyik állítás igaz?",
	"a": "Alapítvány nem, de egyesület létrehozható gazdasági tevékenység folytatására.",
	"b": "Egyesület nem, de alapítvány létrehozható gazdasági tevékenység folytatására.",
	"c": "Sem egyesület, sem alapítvány nem hozható létre gazdasági tevékenység folytatására.",
	"d": "Egyesület és alapítvány is létrehozható gazdasági tevékenység folytatására.",
	"answer": "c"},
"70": {"question":
	"(4_Társasági_Jog) Melyik jellemző a kontinentális (német) társasági modellre?",
	"a": "Erősen megosztott a tulajdonosi szerkezet.",
	"b": "Csekély a társasági formaválaszték.",
	"c": "A társasági szervek élesen elkülönülnek egymástól.",
	"d": "Egyik sem jellemző.",
	"answer": "c"},
"71": {"question":
	"Melyik nem jellemző az angol-amerikai társasági modellre?",
	"a": "A társasági jog szorosan összefonódik a tőkepiac intézményeivel.",
	"b": "A társaságnak egységes vezető szerve van.",
	"c": "A könyvvizsgáló szerepe és felelőssége csekély.",
	"d": "Mindegyik fenti állítás jellemző rá.",
	"answer": "c"},
"72": {"question":
	"Az alábbiak közül melyik szolgálja a közérdeket a társasági jogban?",
	"a": "A diszpozitív szabályozás.",
	"b": "A cégnyilvánosság elve.",
	"c": "A választott bírósági eljárás igénybevételének lehetősége.",
	"d": "Egyik sem.",
	"answer": "b"},
"73": {"question":
	"Melyik társasági forma nem hozható létre egyszemélyes gazdasági társaságként?",
	"a": "Egyszemélyes korlátolt felelősségű társaság.",
	"b": "Egyszemélyes betéti társaság.",
	"c": "Egyszemélyes részvénytársaság.",
	"d": "Mindhárom forma létrehozható.",
	"answer": "b"},
"74": {"question":
	"Melyik társasági forma hozható létre egyszemélyes gazdasági társaságként?",
	"a": "Egyszemélyes betéti társaság.",
	"b": "Egyszemélyes korlátolt felelősségű társaság.",
	"c": "Egyszemélyes közkereseti társaság.",
	"d": "Egyik sem hozható létre.",
	"answer": "b"},
"75": {"question":
	"Hány tag alapíthat közkereseti társaságot?",
	"a": "Legalább egy beltag.",
	"b": "Legalább egy beltag és egy kültag.",
	"c": "Legalább két tag.",
	"d": "Legalább két beltag.",
	"answer": "c"},
"76": {"question":
	"Milyen célt szolgál a társasági formakényszer?",
	"a": "A hitelezők védelmét.",
	"b": "A kisebbségi jogok védelmét.",
	"c": "A társulási szabadság érvényre jutását.",
	"d": "A közérdeket.",
	"answer": "d"},
"77": {"question":
	"Hányféle társasági formában alapítható gazdasági társaság? Sorolja is fel őket.",
	"a": "3, a következők: Bt., Kft., Zrt.",
	"b": "4, a következők: Kkt., Bt., Kft., Zrt.",
	"c": "5, a következők: Kkt., Bt., Kft., Zrt., Nyrt.",
	"d": "Egyik fenti válasz sem megfelelő.",
	"answer": "b"},
"78": {"question":
	"Melyik gazdasági társaság nem rendelkezik jogi személyiséggel?",
	"a": "A korlátolt felelősségű társaság.",
	"b": "A betéti társaság.",
	"c": "A részvénytársaság.",
	"d": "Mindegyik rendelkezik.",
	"answer": "d"},
"79": {"question":
	"Az alábbiak közül melyik szervezet nem rendelkezik jogi személyiséggel?",
	"a": "A korlátolt felelősségű társaság.",
	"b": "Az egyéni cég.",
	"c": "A részvénytársaság.",
	"d": "Mindegyik rendelkezik.",
	"answer": "b"},
"80": {"question":
	"Az alábbiak közül melyik nem lehet apport gazdasági társaság alapítása során?",
	"a": "Egy személyautó.",
	"b": "Egy találmány.",
	"c": "Szerződésen alapuló követelés.",
	"d": "A fentiek mindegyike lehet apport.",
	"answer": "c"},
"81": {"question":
	"Melyik állítás igaz?",
	"a": "Közkereseti társaság nem lehet egy korlátolt felelősségű társaságnak tagja.",
	"b": "Betéti társaság nem lehet egy közkereseti társaságnak tagja.",
	"c": "Korlátolt felelősségű társaság nem lehet egy betéti társaságnak beltagja.",
	"d": "Részvénytársaságnak csak természetes személyek lehetnek a tagjai.",
	"answer": "b"},
"82": {"question":
	"Melyiket nem kezdeményezhetik a G.T. szavazati jogok 5%-ával rendelkező tagjai?",
	"a": "Egyedi könyvvizsgálatot.",
	"b": "A legfőbb szerv összehívását.",
	"c": "Egy tag kizárását.",
	"d": "A társaság igényének érvényesítését egy taggal szemben.",
	"answer": "c"},
"83": {"question":
	"Kik szavazhatnak a gazdasági társaság legfőbb szervének ülésén?",
	"a": "A társaság tagjai.",
	"b": "A társaság tagjai és a vezető tisztségviselő.",
	"c": "A tagok és a felügyelő bizottság tagjai.",
	"d": "A tagok és a cégvezetők.",
	"answer": "a"},
"84": {"question":
	"Melyik tartozik a gazdasági társaság felügyelőbizottságának feladatai közé?",
	"a": "A vezető tisztségviselő megválasztása és visszahívása.",
	"b": "A könyvvizsgáló ellenőrzése.",
	"c": "Az ügyvezetés ellenőrzése.",
	"d": "A beszámoló elkészítése.",
	"answer": "c"},
"85": {"question":
	"A gazdasági társaság melyik szerve kezdeményezheti egy tag kizárását?",
	"a": "A felügyelő bizottság.",
	"b": "A legfőbb szerv.",
	"c": "A vezető tisztségviselő.",
	"d": "Egyik sem, mert tagot nem lehet kizárni.",
	"answer": "b"},
"86": {"question":
	"Melyik szerv dönt a társaság jogutód nélküli megszűnéséről?",
	"a": "A legfőbb szerv.",
	"b": "A felügyelő bizottság.",
	"c": "A vezető tisztségviselő.",
	"d": "A könyvvizsgáló. ",
	"answer": "a"},
"87": {"question":
	"Melyik állítás hamis a Kft-re vonatkozóan?",
	"a": "Kft. esetén a tagok törzsbetétei különböző mértékűek lehetnek.",
	"b": "Az egyes törzsbetétek mértéke legalább 100.000 Ft.",
	"c": "A törzsbetétek összege a törzstőke, melynek minimális mértéke 1 millió Ft.",
	"d": "A tagoknak tetszőleges számú törzsbetéte lehet.",
	"answer": "c"},
"88": {"question":
	"Melyik állítás hamis?",
	"a": "A Bt. alaptőkéje nem lehet kevesebb, mint 100.000 Ft.",
	"b": "A Zrt. alaptőkéje nem lehet kevesebb, mint 5 millió Ft.",
	"c": "Az Nyrt. alaptőkéje nem lehet kevesebb, mint 20 millió Ft.",
	"d": "A közkereseti társaság alaptőkéjére nincs minimális előírás.",
	"answer": "a"},
"89": {"question":
	"Kinek a tulajdona a betéti társaság vagyona?",
	"a": "A beltagok közös tulajdona.",
	"b": "Valamennyi tag közös tulajdona.",
	"c": "A társaság tulajdona.",
	"d": "Az alapító tagok közös tulajdona. ",
	"answer": "c"},
"90": {"question":
	"(5_Egyéb_Jogalanyok) Melyik állítás hamis?",
	"a": "Az egyesülés jogi személyiséggel rendelkezik.",
	"b": "Az egyesülés vagyonát meghaladó tartozásaiért a tagok nem felelnek.",
	"c": "Az egyesülés saját nyereségre nem törekszik.",
	"d": "Az egyesülés célja a tagok tevékenységének összehangolása.",
	"answer": "b"},
"91": {"question":
	"Melyik állítás igaz?",
	"a": "A szövetkezet tagjainak többsége természetes személy.",
	"b": "A szövetkezet valamennyi tagjának személyes közreműködést kell vállalnia.",
	"c": "Szövetkezeti jogvitára választott-bírósági eljárás nem köthető ki.",
	"d": "A szövetkezet nem rendelkezik jogi személyiséggel.",
	"answer": "a"},
"92": {"question":
	"Hány személy alapíthat szövetkezetet?",
	"a": "Legalább 2 személy.",
	"b": "Legalább 3 személy.",
	"c": "Legalább 10 személy.",
	"d": "Egy személy is alapíthat.",
	"answer": "b"},
"93": {"question":
	"Melyik állítás hamis?",
	"a": "A szövetkezet közgyűlésén minden tagnak egy szavazata van.",
	"b": "Szövetkezetnél kötelező a könyvvizsgáló kinevezése.",
	"c": "Szövetkezetnél kötelező a felügyelőbizottság működése. ",
	"d": "A szövetkezet ügyvezetését az igazgatóság látja el.",
	"answer": "b"},
"94": {"question":
	"Melyik szervezet nem vehet részt tagként vállalatcsoportban?",
	"a": "Korlátolt felelősségű társaság.",
	"b": "Szövetkezet.",
	"c": "Egyesülés.",
	"d": "Betéti társaság.",
	"answer": "d"},
"95": {"question":
	"Melyik állítás hamis a vállalatcsoportra vonatkozóan?",
	"a": "Legalább egy uralkodó tag és 3 ellenőrzött tag szükséges hozzá.",
	"b": "A cégbíróság a cégnyilvántartásba bejegyzi.",
	"c": "Az uralkodó tag nem utasíthatja az ellenőrzött tagokat.",
	"d": "Önálló jogi személyiséggel nem rendelkezik.",
	"answer": "c"},
"96": {"question":
	"Az alábbiak közül ki nem lehet egyéni vállalkozó?",
	"a": "17 éves, házasságot kötött személy.",
	"b": "Közkereseti társaság tagja.",
	"c": "Korlátolt felelősségű társaság tagja.",
	"d": "Betéti társaság kültagja.",
	"answer": "b"},
"97": {"question":
	"Melyik szervezet vezeti az egyéni vállalkozók nyilvántartását?",
	"a": "A Nemzeti Adó és Vámhivatal.",
	"b": "A cégbíróság.",
	"c": "A törvényszék.",
	"d": "A céginformációs szolgálat.",
	"answer": "a"},
"98": {"question":
	"Melyik állítás igaz?",
	"a": "Az egyéni vállalkozónak nem lehet alkalmazottja.",
	"b": "A tevékenység csak egyéni vállalkozói igazolvány kiállítása után végezhető.",
	"c": "Az egyéni vállalkozó a kötelezettségeiért csak vállalkozói vagyonával felel. ",
	"d": "Az egyéni vállalkozó köteles személyesen közreműködni a tevékenység folytatásában.",
	"answer": "d"},
"99": {"question":
	"Melyik állítás hamis az egyéni cégre vonatkozóan?",
	"a": "Az egyéni cég jogképes.",
	"b": "Az egyéni cég jogi személyiséggel rendelkezik.",
	"c": "Az egyéni céget a cégbíróság tartja nyilván.",
	"d": "Az egyéni cégnek cégjegyzékszáma van.",
	"answer": "b"},
"100": {"question":
	"Ki alapíthat egyéni céget?",
	"a": "Minden nagykorú, cselekvőképes személy.",
	"b": "Minden nagykorú, cselekvőképes magyar állampolgár.",
	"c": "Aki az egyéni vállalkozói nyilvántartásban szerepel.",
	"d": "Minden nagykorú, cselekvőképes személy, aki nem korlátlanul felelős tagja G.T.-nak.",
	"answer": "c"},
"101": {"question":
	"Az alábbiak közül melyik nem lehet egy egyéni cég alapításkori jegyzett tőkéje?",
	"a": "100.000 Ft plusz egy 200.000 Ft értékű autó.",
	"b": "100.000 Ft plusz egy 100.000 Ft értékű autó.",
	"c": "Egy 300.000 Ft értékű autó. ",
	"d": "100.000 Ft.",
	"answer": "b"},
"102": {"question":
	"Melyik állítás hamis?",
	"a": "A köztestület közfeladatot lát el.",
	"b": "A köztestületet a tagjai szabad elhatározásukkal hozzák létre.",
	"c": "A köztestület jogi személy.",
	"d": "A Magyar Orvosi Kamara is egy köztestület.",
	"answer": "b"},
"103": {"question":
	"Az alábbiak közül melyik nem köztestület?",
	"a": "Magyar Tudományos Akadémia",
	"b": "Magyar Ügyvédi Kamara",
	"c": "Magyar Labdarúgó Szövetség",
	"d": "Magyar Kereskedelmi és Iparkamara",
	"answer": "c"},
"104": {"question":
	"Az alábbiak közül (a,b,c) melyik nem köztestület?",
	"a": "Magyar Tudományos Akadémia",
	"b": "Magyar Ügyvédi Kamara",
	"c": "Magyar Kereskedelmi és Iparkamara",
	"d": "Mindhárom köztestület",
	"answer": "d"},
"105": {"question":
	"Az alábbiak közül melyik nem lehet közhasznú státuszú?",
	"a": "A köztestület.",
	"b": "Az egyesület.",
	"c": "Az alapítvány.",
	"d": "A nonprofit Kft.",
	"answer": "a"},
"106": {"question":
	"Az alábbiak közül melyik lehet csak speciális esetben közhasznú státuszú?",
	"a": "A szövetkezet.",
	"b": "Az egyesület.",
	"c": "Az alapítvány.",
	"d": "A nonprofit Kft.",
	"answer": "a"},
"107": {"question":
	"(6_Cégeljárás) Az alábbi jogalanyok közül melyiknek nincs cégjegyzékszáma?",
	"a": "Az egyesülésnek.",
	"b": "A szövetkezetnek.",
	"c": "Az egyesületnek.",
	"d": "Az egyéni cégnek.",
	"answer": "c"},
"108": {"question":
	"Az alábbiak közül melyik nem a cégbíróság feladata?",
	"a": "Cégbejegyzési eljárás lefolytatása.",
	"b": "Felszámolási eljárás lefolytatása.",
	"c": "Döntés a közhasznúvá minősítésről.",
	"d": "Törvényességi felügyeleti eljárás lefolytatása cégekkel kapcsolatban.",
	"answer": "b"},
"109": {"question":
	"Az alábbi esetek közül melyik fordulhat elő egy céggel kapcsolatban?",
	"a": "Székhelye Vácon van, telephelye nincs, fióktelepe Vácon van.",
	"b": "Székhelye nincs, telephelye Vácon van, fióktelepe Vácon van.",
	"c": "Székhelye Vácon van, telephelye Vácon van, fióktelepe nincs.",
	"d": "Székhelye Vácon van, telephelye Vácon van, fióktelepe Vácon van.",
	"answer": "c"},
"110": {"question":
	"Melyik állítás hamis?",
	"a": "A cégbejegyzési kérelmet csak elektronikus úton lehet benyújtani.",
	"b": "A cégbejegyzési eljárás nem-peres eljárás. ",
	"c": "A kérelmet a létesítő okirat aláírásától számított 30 napon belül kell benyújtani.",
	"d": "A cégbejegyzési eljárás során a jogi képviselet nem kötelező.",
	"answer": "d"},
"111": {"question":
	"Ki dönt egy cég esetén a végelszámolásról?",
	"a": "A cégbíróság.",
	"b": "A cég legfőbb szerve.",
	"c": "A vezető tisztségviselő.",
	"d": "A hitelező(k).",
	"answer": "b"},
"112": {"question":
	"Mikor van helye egyszerűsített cégbejegyzési eljárásnak?",
	"a": "Egyéni cég és Bt. alapításakor.",
	"b": "Ha a cég alaptőkéje nem haladja meg a 100.000 Ft-ot.",
	"c": "Ha a létesítő okirat szerződésminta alapján készült.",
	"d": "Ha a tagok száma egy fő.",
	"answer": "c"},
"113": {"question":
	"Mely cégeknek kell bankszámlával rendelkeznie?",
	"a": "Csak a Zrt.-nek és az Nyrt.-nek.",
	"b": "A gazdasági társaságoknak.",
	"c": "A Zrt.-nek, Nyrt.-nek és a Kft.-nek.",
	"d": "Minden cégnek bankszámlával kell rendelkeznie.",
	"answer": "d"},
"114": {"question":
	"Mennyi egy Zrt. egyszerűsített cégbejegyzési eljárásának illetéke?",
	"a": "10.000 Ft",
	"b": "50.000 Ft",
	"c": "100.000 Ft",
	"d": "Az eljárás illetékmentes.",
	"answer": "b"},
"115": {"question":
	"Mennyi egy Kft. rendes (nem egyszerűsített) cégbejegyzési eljárásának illetéke?",
	"a": "10.000 Ft",
	"b": "50.000 Ft",
	"c": "100.000 Ft",
	"d": "Az eljárás illetékmentes.",
	"answer": "d"},
"116": {"question":
	"Ki képviseli a céget a végelszámolás kezdő időpontja után?",
	"a": "A vezető tisztségviselő.",
	"b": "A vagyonfelügyelő.",
	"c": "A felügyelőbizottság elnöke.",
	"d": "A végelszámoló.",
	"answer": "d"},
"117": {"question":
	"Melyik eljárásnak nem célja a cég jogutód nélküli megszüntetése?",
	"a": "A felszámolási eljárásnak.",
	"b": "A csődeljárásnak.",
	"c": "A végelszámolásnak.",
	"d": "Mindegyiknek az a célja.",
	"answer": "b"},
"118": {"question":
	"Mi a csődeljárás célja?",
	"a": "A fizetésképtelen adós cég jogutód nélküli megszüntetése.",
	"b": "A nem fizetésképtelen cég jogutód nélküli megszüntetése.",
	"c": "Az adós cég fizetési haladékot kap a hitelezőkkel való megegyezés céljából.",
	"d": "Az adós cég vagyonának hatósági árverésen való értékesítése.",
	"answer": "c"},
"119": {"question":
	"Mi a végelszámolás célja?",
	"a": "A fizetésképtelen adós cég jogutód nélküli megszüntetése.",
	"b": "A nem fizetésképtelen cég jogutód nélküli megszüntetése.",
	"c": "Az adós cég fizetési haladékot kap a hitelezőkkel való megegyezés céljából.",
	"d": "Az adós cég vagyonának hatósági árverésen való értékesítése.",
	"answer": "b"},
"120": {"question":
	"Mi a felszámolási eljárás célja?",
	"a": "A fizetésképtelen adós cég jogutód nélküli megszüntetése.",
	"b": "A nem fizetésképtelen cég jogutód nélküli megszüntetése.",
	"c": "Az adós cég fizetési haladékot kap a hitelezőkkel való megegyezés céljából.",
	"d": "Az adós cég vagyonának hatósági árverésen való értékesítése.",
	"answer": "a"},
"121": {"question":
	"Melyik eljárás indul meg a cégbírósághoz benyújtott változásbejegyzési kérelemmel?",
	"a": "Csődeljárás.",
	"b": "Végelszámolás.",
	"c": "Felszámolási eljárás.",
	"d": "A fentiek közül egyik sem.",
	"answer": "b"},
"122": {"question":
	"Melyik eljárást indíthatja meg a hitelező az adós cég ellen?",
	"a": "A végelszámolást.",
	"b": "A csődeljárást.",
	"c": "A felszámolási eljárást.",
	"d": "Kényszer-törlési eljárást.",
	"answer": "c"},
"123": {"question":
	"Melyik eljárást milyen fórumon kell megindítani? Válassza ki a helyeset.",
	"a": "Csődeljárást a cégbíróságon.",
	"b": "Felszámolási eljárást a rendes bíróságon (törvényszéken).",
	"c": "Végelszámolást a rendes bíróságon (törvényszéken).",
	"d": "Cégbejegyzési eljárást a rendes bíróságon (törvényszéken).",
	"answer": "b"},
"124": {"question":
	"(7_Dologi_Jog) Kivel szemben nem illeti meg a birtokvédelem joga a birtokost?",
	"a": "A tulajdonossal szemben.",
	"b": "A hitelezővel szemben.",
	"c": "Azzal szemben, akitől a dolgot tilos önhatalommal szerezte meg.",
	"d": "Kivétel nélkül mindenkivel szemben megilleti.",
	"answer": "c"},
"125": {"question":
	"Melyek a birtokvédelem megengedett eszközei?",
	"a": "Minden esetben a bírósághoz kell fordulni.",
	"b": "Minden esetben a jegyzőhöz kell fordulni.",
	"c": "Minden esetben a rendőrséghez kell fordulni.",
	"d": "Bírósághoz vagy jegyzőhöz fordulás, speciális esetben önhatalommal való fellépés.",
	"answer": "d"},
"126": {"question":
	"Az alábbiak közül melyik nem tartozik a \"szükséges költségek\" körébe?",
	"a": "Az állagmegóvásra fordított költségek.",
	"b": "A kártól való megóvásra fordított költségek.",
	"c": "A dolog értékét növelő költségek.",
	"d": "Mindhárom fenti a \"szükséges\" költségek körébe tartozik.",
	"answer": "c"},
"127": {"question":
	"Milyen költségei megtérítését követelheti a rosszhiszemű jogalap nélküli birtokos?",
	"a": "A dologra fordított szükséges költségei megtérítését.",
	"b": "A dologra fordított hasznos költségei megtérítését.",
	"c": "A szükséges és hasznos költségei megtérítését is követelheti.",
	"d": "Semmilyen költségei megtérítését nem követelheti.",
	"answer": "a"},
"128": {"question":
	"Az alábbiak közül melyik nem lehet tulajdonjog tárgya?",
	"a": "Az elektromos energia (villamos áram).",
	"b": "A szellemi alkotás.",
	"c": "Az állatok.",
	"d": "Az értékpapír.",
	"answer": "b"},
"129": {"question":
	"Az alábbi 3 állítás (a,b,c) közül melyik hamis?",
	"a": "Az ingatlan tulajdonosa a használat jogát másnak átengedheti.",
	"b": "Az ingatlan tulajdonosa a tulajdonjogát másra átruházhatja.",
	"c": "Az ingatlan tulajdonosa a tulajdonjogával felhagyhat.",
	"d": "Mindhárom előző állítás igaz.",
	"answer": "c"},
"130": {"question":
	"Melyik állítás igaz?",
	"a": "Szükséghelyzetben okozott kár esetén a (károsult) tulajdonos kártérítést követelhet.",
	"b": "Közérdekű használat esetén a tulajdonost kártérítés illeti meg.",
	"c": "Kisajátítás esetén a tulajdonost kártérítés illeti meg.",
	"d": "Mindhárom fenti esetben kártalanítás és nem kártérítés illeti meg a tulajdonost.",
	"answer": "d"},
"131": {"question":
	"Melyik állítás igaz?",
	"a": "Jogellenes károkozás esetén a (károsult) tulajdonos kártérítést követelhet.",
	"b": "Közérdekű használat esetén a tulajdonost kártérítés illeti meg.",
	"c": "Kisajátítás esetén a tulajdonost kártérítés illeti meg.",
	"d": "Mindhárom fenti esetben kártalanítás és nem kártérítés illeti meg a tulajdonost.",
	"answer": "a"},
"132": {"question":
	"Az alábbiak közül melyik tulajdonszerzési mód származékos?",
	"a": "Tulajdon átruházás.",
	"b": "Hatósági árverés útján való tulajdonszerzés.",
	"c": "Elbirtoklás.",
	"d": "Kisajátítás.",
	"answer": "a"},
"133": {"question":
	"Mikor száll át az ingatlan tulajdonjoga átruházás esetén?",
	"a": "A szerződés megkötésekor.",
	"b": "A felek által a szerződésben meghatározott időpontban.",
	"c": "A birtokbaadáskor.",
	"d": "Az új tulajdonosnak az ingatlan-nyilvántartásba való bejegyzésével.",
	"answer": "d"},
"134": {"question":
	"Melyik állítás hamis?",
	"a": "Kisajátítás csak közérdekű célra lehetséges.",
	"b": "Kisajátítani csak ingatlant lehet.",
	"c": "A kisajátítást csak az állam kérheti.",
	"d": "A kisajátítási eljárás során a kisajátítási hatóság tárgyalást tart.",
	"answer": "c"},
"135": {"question":
	"Melyik állítás igaz?",
	"a": "Az ingatlan elbirtoklási ideje 10 év.",
	"b": "Bűncselekménnyel megszerzett dolgon nem következik be az elbirtoklás.",
	"c": "Ingatlan elbirtoklásához a tulajdonjogot az ingatlan-nyilvántartásba be kell jegyezni.",
	"d": "Elbirtoklással csak ingó dolog tulajdonjogát lehet megszerezni.",
	"answer": "b"},
"136": {"question":
	"Melyik állítás hamis?",
	"a": "Villamoson felejtett dolgon nem lehet találással tulajdont szerezni.",
	"b": "Gazdátlan dolgon nem lehet találással tulajdont szerezni.",
	"c": "A találó csak akkor válik tulajdonossá, ha a korábbi tulajdonos 1 éven belül nem jelentkezik.",
	"d": "A találás származékos tulajdonszerzési mód.",
	"answer": "d"},
"137": {"question":
	"Melyik állítás hamis a zálogjogviszony esetén?",
	"a": "A jogviszony alanya a személyes kötelezett és a zálogjogosult.",
	"b": "A zálogtárgy tulajdonosa a zálogkötelezett.",
	"c": "A zálogjogosult kielégítési joga akkor nyílik meg, ha a személyes kötelezett nem teljesít. ",
	"d": "A zálogkötelezett csak a zálogtárggyal felel a zálogjogosultnak. ",
	"answer": "a"},
"138": {"question":
	"Melyik állítás hamis a zálogjogviszony esetén?",
	"a": "A jogviszony alanya a zálogkötelezett és a zálogjogosult.",
	"b": "A zálogtárgy tulajdonosa a zálogjogosult.",
	"c": "A zálogjogosult kielégítési joga akkor nyílik meg, ha a személyes kötelezett nem teljesít. ",
	"d": "A zálogkötelezett csak a zálogtárggyal felel a zálogjogosultnak. ",
	"answer": "b"},
"139": {"question":
	"Melyik állítás hamis a zálogjogviszony esetén?",
	"a": "A jogviszony alanya a zálogkötelezett és a zálogjogosult.",
	"b": "A zálogtárgy tulajdonosa a zálogkötelezett.",
	"c": "A zálogjogosult kielégítési joga akkor nyílik meg, ha a személyes kötelezett nem teljesít. ",
	"d": "A zálogkötelezett teljes vagyonával felel a zálogjogosultnak. ",
	"answer": "d"},
"140": {"question":
	"Melyik állítás hamis a zálogjogviszony esetén?",
	"a": "Az óvadék is a zálog egy fajtája.",
	"b": "Jelzálogjog csak ingatlanon alapítható.",
	"c": "Kézizálogjog tárgya csak ingó dolog lehet.",
	"d": "A személyes kötelezett és a zálogkötelezett lehet ugyanaz a személy.",
	"answer": "b"},
"141": {"question":
	"Melyiket nem teheti meg a haszonélvezeti jog jogosultja?",
	"a": "A dolgot nem hasznosíthatja.",
	"b": "A haszonélvezeti jogot nem ruházhatja át.",
	"c": "A dolgot nem tarthatja a birtokában.",
	"d": "A fenti 3 mindegyikét megteheti.",
	"answer": "b"},
"142": {"question":
	"Az alábbi esetek közül melyikben nem használhatja a birtokos a dolgot?",
	"a": "Haszonkölcsön esetén.",
	"b": "Kézizálog esetén.",
	"c": "Haszonélvezeti jog esetén.",
	"d": "A fenti esetek mindegyikében használhatja.",
	"answer": "b"},
"143": {"question":
	"(8_Kötelmi_Jog) Az alábbiak közül melyik magatartásra nem irányulhat a kötelem?",
	"a": "Valaminek az adására.",
	"b": "Valamilyen tevékenység elvégzésére.",
	"c": "Valamitől való tartózkodásra.",
	"d": "Mindegyik fenti magatartásra irányulhat.",
	"answer": "d"},
"144": {"question":
	"Az alábbiak közül melyikből nem keletkezhet kötelem?",
	"a": "Jogalap nélküli gazdagodásból.",
	"b": "Személyiségi jog megsértéséből.",
	"c": "Utaló magatartásból.",
	"d": "A fentiek mindegyikéből keletkezhet.",
	"answer": "d"},
"145": {"question":
	"Az alábbiak közül melyik károkozás jogellenes?",
	"a": "A károsult beleegyezésével okozott kár.",
	"b": "Jogtalan támadás elhárítása során a támadónak okozott kár.",
	"c": "Szükséghelyzetben okozott kár.",
	"d": "A fentiek egyike sem jogellenes.",
	"answer": "d"},
"146": {"question":
	"Az alábbiak közül melyik esetben keletkezik kötelem (kötelezettség)?",
	"a": "Jogtalan támadás elhárítása során a támadónak okozott kár esetén.",
	"b": "A károsult beleegyezésével okozott kár esetén.",
	"c": "Szükséghelyzetben okozott kár esetén.",
	"d": "Egyik esetben sem keletkezik.",
	"answer": "c"},
"147": {"question":
	"Melyik állítás igaz?",
	"a": "Kártérítési kötelezettséghez nem szükséges a kár bekövetkezése.",
	"b": "A kár bekövetkezését a károsultnak kell bizonyítania.",
	"c": "Akit személyiségi jogában megsértenek, kártérítést követelhet.",
	"d": "Akit személyiségi jogában megsértenek, kártalanítást követelhet. ",
	"answer": "b"},
"148": {"question":
	"Melyik állítás igaz?",
	"a": "A sérelemdíj megállapításához nem szükséges kár bekövetkezése.",
	"b": "A becsületsértésért büntetőeljárásban kérhető sérelemdíj.",
	"c": "A becsületsértésért megítélt pénzbüntetés a sértettet illeti.",
	"d": "A személyiségi jog megsértése bűncselekmény.",
	"answer": "a"},
"149": {"question":
	"Melyik állítás igaz?",
	"a": "Az ajándékozás egyoldalú nyilatkozat.",
	"b": "Ha valaki nyilvánosan díjat ígér egy teljesítményért, nem köteles azt teljesíteni.",
	"c": "Ha valaki közérdekű célra vállal kötelezettséget, az egy szerződés az állammal.",
	"d": "A szerződés soha nem lehet egyoldalú nyilatkozat.",
	"answer": "d"},
"150": {"question":
	"Melyik állítás igaz?",
	"a": "Ha valaki tévedésből többet utal át a vételárnál, nem követelheti azt vissza.",
	"b": "Ha valaki tévedésből többet utal át a vételárnál, az ajándékozásnak minősül.",
	"c": "Ha valaki tévedésből többet utal át, a többletet a másik köteles visszatéríteni.",
	"d": "Ha valaki tévedésből többet utal át, a többlet felét visszakövetelheti.",
	"answer": "c"},
"151": {"question":
	"Melyik állítás igaz?",
	"a": "Értékpapírt csak írásban, okirati formában lehet kibocsátani.",
	"b": "Az értékpapír egy szerződés a kibocsátó és a jogosult között.",
	"c": "Az értékpapírban foglalt követelés nem átruházható.",
	"d": "A befektetési jegy az értékpapír egyik fajtája.",
	"answer": "d"},
"152": {"question":
	"Melyik állítás hamis?",
	"a": "A váltó hitelviszonyt megtestesítő értékpapír.",
	"b": "A kötvény tagsági jogokat megtestesítő értékpapír.",
	"c": "A részvény tagsági jogokat megtestesítő értékpapír.",
	"d": "A közraktári jegy dologi jogot megtestesítő értékpapír.",
	"answer": "b"},
"153": {"question":
	"Az alábbi esetek közül melyikben nem szűnik meg a kötelem (fő szabály szerint)?",
	"a": "A szolgáltatás teljesítésével.",
	"b": "A kötelezett halálával.",
	"c": "Tartozásátvállalás esetén.",
	"d": "A jogosult jogutód nélküli megszűnése esetén.",
	"answer": "c"},
"154": {"question":
	"Hányféle formában lehet jognyilatkozatot tenni? Sorolja is fel őket.",
	"a": "2, amelyek a következők: szóban, írásban",
	"b": "3, amelyek a következők: szóban, írásban, ráutaló magatartással",
	"c": "4, amelyek a következők: szóban, írásban, elektronikus úton, ráutaló magatartással",
	"d": "5, amelyek a következők: szóban, írásban, elektronikus úton, ráutaló magatartással, képviselő által",
	"answer": "b"},
"155": {"question":
	"Mikor minősül a jognyilatkozat írásba foglaltnak?",
	"a": "Ha a nyilatkozó saját kezűleg írta.",
	"b": "Ha két tanú aláírta.",
	"c": "Ha a nyilatkozó aláírta.",
	"d": "Ha ügyvéd aláírta.",
	"answer": "c"},
"156": {"question":
	"Az alábbiak közül ki nem készíthet közokiratot?",
	"a": "Ügyvéd.",
	"b": "Bíróság.",
	"c": "Közjegyző.",
	"d": "Közigazgatási szerv.",
	"answer": "a"},
"157": {"question":
	"Melyik állítás hamis?",
	"a": "A képviseleti jog alapulhat vállalkozási szerződésen.",
	"b": "A képviseleti jog alapulhat létesítő okiraton.",
	"c": "A képviseleti jog alapulhat meghatalmazáson.",
	"d": "A képviseleti jog alapulhat jogszabályon. ",
	"answer": "a"},
"158": {"question":
	"Melyik állítás igaz?",
	"a": "Jognyilatkozatot csak személyesen lehet tenni.",
	"b": "A képviselő jognyilatkozata a képviselőt jogosítja és kötelezi.",
	"c": "A meghatalmazás egyoldalú jognyilatkozat.",
	"d": "A meghatalmazás szóban nem érvényes.",
	"answer": "c"},
"159": {"question":
	"Hány év alatt évülnek el a követelések (fő szabály szerint)?",
	"a": "3 év alatt.",
	"b": "5 év alatt. ",
	"c": "1 év alatt.",
	"d": "A követelések nem évülnek el.",
	"answer": "b"},
"160": {"question":
	"Melyik állítás igaz?",
	"a": "Elévült követelés bírósági eljárásban csak jogi képviselettel érvényesíthető.",
	"b": "Ha valaki elévült követelést teljesít, utóbb visszakövetelheti azt.",
	"c": "A fogadásból eredő követelés bíróság előtt 1 évig érvényesíthető.",
	"d": "Mindhárom fenti állítás hamis.",
	"answer": "d"},
"161": {"question":
	"(9_Szerződések) Melyik állítás a legpontosabb a szerződésre vonatkozóan?",
	"a": "A szerződés a felek egyidejű és egybehangzó jognyilatkozata.",
	"b": "A szerződés a felek kölcsönös és egyidejű jognyilatkozata.",
	"c": "A szerződés a felek kölcsönös és egybehangzó jognyilatkozata.",
	"d": "A szerződés a felek kölcsönös, egybehangzó és egyidejű jognyilatkozata.",
	"answer": "c"},
"162": {"question":
	"Az alábbiak közül melyik nem tartozik a szerződési jog legfontosabb alapelvei közé?",
	"a": "A szerződési szabadság elve.",
	"b": "A visszterhesség vélelme.",
	"c": "Az együttműködési és tájékoztatási kötelezettség.",
	"d": "A gyengébb fél érdekei védelmének az elve.",
	"answer": "d"},
"163": {"question":
	"Mi történik ha a felek szerződési nyilatkozatai lényeges kérdésben eltérnek?",
	"a": "A szerződés megtámadható lesz.",
	"b": "A szerződés érvénytelen lesz.",
	"c": "A szerződés nem jön létre.",
	"d": "A bíróság ítéletével kiküszöböli az eltérést.",
	"answer": "c"},
"164": {"question":
	"Melyik állítás hamis az ajánlatra vonatkozóan?",
	"a": "Aki ajánlatot tesz, meghatározott ideig kötve van az ajánlathoz.",
	"b": "Az ajánlati kötöttség idejét a felek közösen határozzák meg.",
	"c": "Ha a másik fél határidőben elfogadja az ajánlatot, a szerződés létrejön.",
	"d": "Ha a másik fél eltérő tartalommal fogadja el, az új ajánlatnak minősül.",
	"answer": "b"},
"165": {"question":
	"Az alábbiak közül melyikből nem származhat szerződéskötési kötelezettség?",
	"a": "Jogszabályból.",
	"b": "Versenyeztetési eljárásból.",
	"c": "Előszerződésből.",
	"d": "Mindháromból fentiből származhat.",
	"answer": "d"},
"166": {"question":
	"Melyik állítás igaz?",
	"a": "Az Általános Szerződési Feltételeket a felek előre, közösen határozzák meg.",
	"b": "A fogyasztó csak természetes személy lehet.",
	"c": "Távollévők között kötött szerződés létrejöhet két vállalkozás között is.",
	"d": "Fogyasztói szerződés esetén a fogyasztót 14 napon belül elállási jog illeti meg.",
	"answer": "b"},
"167": {"question":
	"Az érvénytelenségnek hányféle formája van a polgári jogban, és melyek ezek?",
	"a": "3, éspedig a következők: semmisség, megtámadhatóság, lehetetlenség",
	"b": "2, éspedig a következők: semmisség, megtámadhatóság",
	"c": "1, éspedig a következő: semmisség",
	"d": "A polgári jogban nem létezik az érvénytelenség fogalma.",
	"answer": "b"},
"168": {"question":
	"Az alábbiak közül melyik a célzott joghatás hibája?",
	"a": "A tévedés.",
	"b": "A megtévesztés.",
	"c": "A jó erkölcsbe ütközés.",
	"d": "A jogellenes fenyegetés.",
	"answer": "c"},
"169": {"question":
	"Az alábbi esetek közül melyikben merül fel a szerződési akarat hibája?",
	"a": "A megtévesztéssel kötött szerződés.",
	"b": "Az uzsorás szerződés.",
	"c": "A jogszabályba ütköző szerződés.",
	"d": "A nem megfelelő formában megkötött szerződés.",
	"answer": "a"},
"170": {"question":
	"Melyik állítás igaz?",
	"a": "A jogszabályba ütköző szerződés megtámadható.",
	"b": "A jogellenes fenyegetéssel kötött szerződés semmis.",
	"c": "Az uzsorás szerződés semmis.",
	"d": "Mindhárom fenti állítás hamis.",
	"answer": "c"},
"171": {"question":
	"Az alábbiak közül melyiknek a jogkövetkezménye a szerződés semmissége?",
	"a": "A feltűnő értékaránytalansággal kötött szerződés.",
	"b": "A megtévesztéssel kötött szerződés.",
	"c": "A jó erkölcsbe ütköző szerződés.",
	"d": "A jogellenes fenyegetéssel kötött szerződés.",
	"answer": "c"},
"172": {"question":
	"Melyik állítás hamis?",
	"a": "Érvénytelen szerződés alapján a teljesítés nem követelhető.",
	"b": "Hatálytalan szerződés alapján a teljesítés nem követelhető.",
	"c": "Érvénytelen szerződés alapján teljesített szolgáltatást nem lehet visszakövetelni.",
	"d": "Érvénytelen szerződés utóbb érvényessé válhat a felek akaratából.",
	"answer": "c"},
"173": {"question":
	"Szerződésszegés esetén melyiket nem teheti meg a sérelmet szenvedett fél?",
	"a": "Továbbra is követelheti a teljesítést.",
	"b": "Fedezeti szerződést köthet és követelheti annak költségeit.",
	"c": "A nála levő, a másik fél tulajdonát képező dologból kielégítést kereshet.",
	"d": "A saját szolgáltatását visszatarthatja.",
	"answer": "c"},
"174": {"question":
	"Az alábbiak közül melyik nem tartozik a szerződésszegés nevesített esetei közé?",
	"a": "A késedelem.",
	"b": "Az elállás.",
	"c": "A lehetetlenülés.",
	"d": "A teljesítés megtagadása.",
	"answer": "b"},
"175": {"question":
	"Melyik állítás hamis?",
	"a": "Ha jogosult késedelembe esik a kárveszély átszáll rá.",
	"b": "Ha a hiba a teljesítés után keletkezett, szavatossági igény nem érvényesíthető.",
	"c": "Ha a teljesítés lehetetlenné válik, a szerződés megtámadható.",
	"d": "A kellékszavatossági igények 1 év alatt elévülnek.",
	"answer": "c"},
"176": {"question":
	"Mennyi a kellékszavatossági igények elévülési ideje fogyasztói szerződés esetén?",
	"a": "1 év",
	"b": "2 év",
	"c": "5 év",
	"d": "Fogyasztói szerződés esetén ezen igények nem évülnek el.",
	"answer": "b"},
"177": {"question":
	"Az alábbiak közül melyiket nem választhatja a fogyasztó termékszavatossági igényként?",
	"a": "A kijavítást.",
	"b": "A kicserélést.",
	"c": "Az elállást.",
	"d": "Mindhármat választhatja.",
	"answer": "c"},
"178": {"question":
	"Melyik állítás igaz a jótállásra vonatkozóan?",
	"a": "A jótállás minden szerződés esetén megilleti a szolgáltatás jogosultját.",
	"b": "A szavatosság és a jótállás ugyanazt jelenti.",
	"c": "A jótállási idő nem lehet hosszabb 5 évnél.",
	"d": "A jótállás lehet önkéntes vagy kötelező.",
	"answer": "d"},
"179": {"question":
	"Az alábbi alanyváltozások közül melyik háromoldalú megállapodás?",
	"a": "A jogátruházás.",
	"b": "Az engedményezés.",
	"c": "A tartozásátvállalás.",
	"d": "Egyik sem.",
	"answer": "c"},
"180": {"question":
	"Melyik állítás hamis?",
	"a": "A szerződés felmondása egyoldalú jognyilatkozat.",
	"b": "Az elállás a jövőre nézve szünteti meg a szerződést.",
	"c": "A szerződés felbontása a felek közös nyilatkozata.",
	"d": "A felek a szerződést bármikor megszüntethetik.",
	"answer": "b"},
"181": {"question":
	"(10_Egyes_Szerződések) Az alábbiak közül melyik jog nem alapítható (szerezhető meg) bármikor?",
	"a": "Az eladási jog.",
	"b": "A vételi jog.",
	"c": "A visszavásárlási jog.",
	"d": "Az elővásárlási jog.",
	"answer": "c"},
"182": {"question":
	"Melyik állítás hamis?",
	"a": "Az eladási jog jogosultja egyoldalú nyilatkozattal eladhatja a dolgot.",
	"b": "Az elővásárlási jog jogosultja egyoldalú nyilatkozattal megveheti a dolgot.",
	"c": "A vételi jog jogosultja egyoldalú nyilatkozattal megveheti a dolgot.",
	"d": "A visszavásárlási jog jogosultja egyoldalú nyilatkozattal megveheti a dolgot.",
	"answer": "b"},
"183": {"question":
	"Az alábbiak közül melyiket nem kell az ingatlan-nyilvántartásba bejegyeztetni?",
	"a": "A tulajdonjog fenntartást.",
	"b": "A vételi jogot.",
	"c": "Az eladási jogot.",
	"d": "Mindhárom fentit be kell jegyeztetni.",
	"answer": "d"},
"184": {"question":
	"Az alábbiak közül melyiket nem kell az ingatlan-nyilvántartásba bejegyeztetni?",
	"a": "A tulajdonjog fenntartást.",
	"b": "A vételi jogot.",
	"c": "Az elbirtoklás megkezdődését.",
	"d": "Mindhárom fentit be kell jegyeztetni.",
	"answer": "c"},
"185": {"question":
	"Melyik állítás igaz?",
	"a": "Az ajándékozás egyoldalú jognyilatkozat.",
	"b": "Ajándékozás történhet ellenérték fejében is.",
	"c": "Az ajándék egyes esetekben visszakövetelhető.",
	"d": "Az ajándékozásra a jogalap nélküli gazdagodás szabályait kell alkalmazni.",
	"answer": "c"},
"186": {"question":
	"Melyik állítás hamis a vállalkozási szerződésre vonatkozóan?",
	"a": "A vállalkozási szerződés eredménykötelem.",
	"b": "A megrendelő a teljesítés előtt bármikor elállhat.",
	"c": "A vállalkozó a teljesítés előtt bármikor elállhat.",
	"d": "A vállalkozót törvényes zálogjog illeti meg.",
	"answer": "c"},
"187": {"question":
	"Az alábbiak közül melyik nem a vállalkozási szerződés altípusa?",
	"a": "A tervezési szerződés.",
	"b": "A fuvarozási szerződés.",
	"c": "A szállítmányozási szerződés.",
	"d": "A kivitelezési szerződés.",
	"answer": "c"},
"188": {"question":
	"Melyik állítás hamis?",
	"a": "A megbízási szerződés eredménykötelem.",
	"b": "A megbízó a szerződést felmondhatja.",
	"c": "A megbízott a szerződést felmondhatja.",
	"d": "A megbízottat törvényes zálogjog illeti meg.",
	"answer": "a"},
"189": {"question":
	"Az alábbiak közül melyik nem a megbízási szerződés altípusa?",
	"a": "A bizományi szerződés.",
	"b": "A szállítmányozási szerződés.",
	"c": "A közvetítői szerződés.",
	"d": "A fuvarozási szerződés.",
	"answer": "d"},
"190": {"question":
	"(11-13_Egyebek) Az alábbiak közül melyik nem minősül különleges személyes adatnak?",
	"a": "Az érintett egészségi állapota.",
	"b": "Az érintett vagyoni helyzete.",
	"c": "Az érintett vallási meggyőződése.",
	"d": "Az érintett politikai véleménye.",
	"answer": "b"},
"191": {"question":
	"Az alábbi műveletek közül melyik nem minősül adatkezelésnek?",
	"a": "Az adatok gyűjtése.",
	"b": "Az adatok tárolása.",
	"c": "Az adatok lekérdezése.",
	"d": "Mind a három fenti művelet adatkezelésnek minősül.",
	"answer": "d"},
"192": {"question":
	"Az alábbi műveletek közül melyik minősül adatfeldolgozásnak?",
	"a": "Az adatok gyűjtése.",
	"b": "Az adatkezelő megbízásából végzett adatkezelési műveletek elvégzése.",
	"c": "Az adatok lekérdezése.",
	"d": "Mind a három fenti művelet adatfeldolgozásnak minősül.",
	"answer": "b"},
"193": {"question":
	"Az alábbi 3 állítás (a,b,c) közül melyik hamis?",
	"a": "Személyes adatok kezeléséhez elég ha az érintett szóban hozzájárult.",
	"b": "Különleges adat csak törvényi előírás alapján kezelhető.",
	"c": "Bűnügyi személyes adatot csak állami vagy önkormányzati szerv kezelhet.",
	"d": "Mind a három fenti állítás igaz.",
	"answer": "b"},
"194": {"question":
	"Az alábbiak közül melyik esetben nem tiltakozhat az érintett személyes adatának kezelése ellen?",
	"a": "Közvetlen üzletszerzés céljára történő felhasználás esetén.",
	"b": "Közvélemény kutatási célú felhasználás esetén.",
	"c": "Tudományos célú felhasználás esetén.",
	"d": "Mindhárom fenti esetben tiltakozhat.",
	"answer": "d"},
"195": {"question":
	"Az alábbiak közül melyik alkotás nem áll a szerzői jog védelme alatt?",
	"a": "Ötlet, eljárás.",
	"b": "Szoftver",
	"c": "Adatbázis",
	"d": "Térkép",
	"answer": "a"},
"196": {"question":
	"Az alábbi adatkezelők közül melyiknél nem kötelező adatvédelmi tisztviselő alkalmazása?",
	"a": "Állami feladatot ellátó adatkezelő szervezetnél.",
	"b": "Bíróságoknál.",
	"c": "Közfeladatot ellátó adatkezelő szervezetnél.",
	"d": "Mindhárom fenti esetben kötelező.",
	"answer": "b"},
"197": {"question":
	"Mennyi ideig védi a szerzői jog a művet?",
	"a": "50 évig.",
	"b": "A szerző élete végéig.",
	"c": "A szerző életében és halála után 70 évig.",
	"d": "20 évig.",
	"answer": "c"},
"198": {"question":
	"Az alábbiak jogok közül melyikkel nem rendelkezik a személyes adatok érintettje?",
	"a": "A törléshez való joggal.",
	"b": "A helyesbítéshez való joggal.",
	"c": "Az előzetes tájékozódáshoz való joggal.",
	"d": "Mindhárom fenti joggal rendelkezik.",
	"answer": "d"},
"199": {"question":
	"Az alábbi állítások közül melyik hamis?",
	"a": "A NAIH elnökét a köztársasági elnök nevezi ki 9 évre.",
	"b": "Az adatigénylésnek a közfeladatot ellátó szerv 15 napon belül köteles eleget tenni.",
	"c": "Az adatigénylés költségtérítése a kézbesítés költségét nem tartalmazhatja.",
	"d": "Adatigénylés benyújtása esetén a jogi képviselet nem kötelező.",
	"answer": "c"},
"200": {"question":
	"Melyik állítás hamis?",
	"a": "A felhasználási engedély korlátozható valamely területre.",
	"b": "A felhasználási engedély korlátozható megadott időtartamra.",
	"c": "A felhasználási engedély korlátozható valamely felhasználási módra.",
	"d": "A felhasználási engedély szóban is érvényes.",
	"answer": "d"},
"201": {"question":
	"Mennyi ideig védi a szabadalmi oltalom a találmányt?",
	"a": "10 évig.",
	"b": "20 évig.",
	"c": "A szabadalmas élete végéig.",
	"d": "A szabadalmas életében és halála után 20 évig.",
	"answer": "b"},
"202": {"question":
	"Az alábbi műveletek közül melyik nem minősül adatkezelésnek?",
	"a": "Az adatok gyűjtése.",
	"b": "Az adatkezelési műveletekhez kapcsolódó technikai feladatok elvégzése.",
	"c": "Az adatok lekérdezése.",
	"d": "Mind a három fenti művelet adatkezelésnek minősül.",
	"answer": "b"},
"203": {"question":
	"Az alábbiak közül melyik esetben nem tiltakozhat az érintett személyes adatának kezelése ellen?",
	"a": "Közvetlen üzletszerzés céljára történő felhasználás esetén.",
	"b": "Közvélemény kutatási célú felhasználás esetén.",
	"c": "Ha az adatkezelést közérdekű célból törvény rendeli el.",
	"d": "Mindhárom fenti esetben tiltakozhat.",
	"answer": "c"}

}`
